USE [master]
GO

/****** Object:  Database [LMSDB]    Script Date: 11-Apr-22 11:30:43 PM ******/
CREATE DATABASE [LMSDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LMSDB', FILENAME = N'E:\SAMESTER 8\OOP2\Database\LMSDB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LMSDB_log', FILENAME = N'E:\SAMESTER 8\OOP2\Database\LMSDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LMSDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LMSDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LMSDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LMSDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LMSDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LMSDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LMSDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [LMSDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LMSDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LMSDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LMSDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LMSDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LMSDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LMSDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LMSDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LMSDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LMSDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LMSDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LMSDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LMSDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LMSDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LMSDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LMSDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LMSDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LMSDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LMSDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LMSDB] SET  MULTI_USER 
GO

ALTER DATABASE [LMSDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LMSDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LMSDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LMSDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LMSDB] SET  READ_WRITE 
GO

